import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Main from '@/components/Main'
import About from '@/components/About'
import Features from '@/components/Features'
import Cards from '@/components/Cards'
import DownloadApp from '@/components/DownloadApp'
import Contact from '@/components/Contact'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Payday</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='h-[90vh] sm:h-[97.7vh] lg:h-[107vh] bg-gradient-to-b from-white to to-[#c6dcfb]'>
        <Navbar />
        <Main />
        <Features />
        <About />
        <Cards />
        <DownloadApp />
        <Contact />
      </div>

    </div>
  )
}
